### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Contra686386** [Alb-310/Geogramint#10]
I installed Geogramint-Installer-v1.2.exe file but I get an error when I run the application, what could be the reason for this ? Please see the screenshot.
![image (8)](https://user-images.githubusercontent.com/104632554/235925534-cf0886c7-9615-44b4-8865-5df8fda1237c.png)

**Comment by Alb-310** [comment]
Hello, it may be caused by the directory where Geogramint is installed.
Try to run it as Administrator and if it doesn't work try to reinstall Geogramint in an other directory like for example a folder on your Desktop to test

**Comment by Contra686386** [comment]
Hello, Alb-310, thanks for the reply. I did as you said and it's working now, many thanks.
