### ISSUE TITLE
PDF creating problem

### ISSUE THREAD

**Issue by Kafel23** [Alb-310/Geogramint#16]
Hi there... Still having problem creating PDF report.... can it be solved anyway???? Thanks

**Comment by Alb-310** [comment]
Hello👋🏻,
Are you running Geogramint in its last version ? (1.3)

If yes, can you please send the logs of the problem when generating a pdf report ?

**Comment by Kafel23** [comment]
Version 1.3

[INFO   ] ====== WebDriver manager ======
[INFO   ] Get LATEST chromedriver version for google-chrome
[DEBUG  ] [Starting new HTTPS connection (1)] chromedriver.storage.googleapis.com:443
[DEBUG  ] [https          ]//chromedriver.storage.googleapis.com:443 "GET /LATEST_RELEASE HTTP/1.1" 200 13
[INFO   ] [About to download new driver from https]//chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip
[DEBUG  ] [Starting new HTTPS connection (1)] chromedriver.storage.googleapis.com:443
[DEBUG  ] [https          ]//chromedriver.storage.googleapis.com:443 "GET /114.0.5735.90/chromedriver_win32.zip HTTP/1.1" 200 6603303
[INFO   ] Driver downloading response is 200
[INFO   ] Get LATEST chromedriver version for google-chrome
[DEBUG  ] [Starting new HTTPS connection (1)] chromedriver.storage.googleapis.com:443
[DEBUG  ] [https          ]//chromedriver.storage.googleapis.com:443 "GET /LATEST_RELEASE HTTP/1.1" 200 13
[INFO   ] Get LATEST chromedriver version for google-chrome
[DEBUG  ] [Starting new HTTPS connection (1)] chromedriver.storage.googleapis.com:443
[DEBUG  ] [https          ]//chromedriver.storage.googleapis.com:443 "GET /LATEST_RELEASE HTTP/1.1" 200 13
[INFO   ] [Driver has been saved in cache [C]\Users\New\.wdm\drivers\chromedriver\win64\114.0.5735.90]
[DEBUG  ] [Started executable] `C:\Users\New\.wdm\drivers\chromedriver\win64\114.0.5735.90\chromedriver.exe` in a child process with pid: 9356
[DEBUG  ] [POST http   ]//localhost:52831/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"excludeSwitches": ["enable-logging"], "extensions": [], "args": ["--headless", "window-size=1920x1080"]}}}}
[DEBUG  ] [Starting new HTTP connection (1)] localhost:52831
[DEBUG  ] [http          ]//localhost:52831 "POST /session HTTP/1.1" 500 846
[DEBUG  ] [Remote response] status=500 | data={"value":{"error":"unknown error","message":"unknown error: cannot find Chrome binary","stacktrace":"Backtrace:\n\tGetHandleVerifier [0x0042A813+48355]\n\t(No symbol) [0x003BC4B1]\n\t(No symbol) [0x002C5358]\n\t(No symbol) [0x002E1A9E]\n\t(No symbol) [0x002E0579]\n\t(No symbol) [0x00310C55]\n\t(No symbol) [0x0031093C]\n\t(No symbol) [0x0030A536]\n\t(No symbol) [0x002E82DC]\n\t(No symbol) [0x002E93DD]\n\tGetHandleVerifier [0x0068AABD+2539405]\n\tGetHandleVerifier [0x006CA78F+2800735]\n\tGetHandleVerifier [0x006C456C+2775612]\n\tGetHandleVerifier [0x004B51E0+616112]\n\t(No symbol) [0x003C5F8C]\n\t(No symbol) [0x003C2328]\n\t(No symbol) [0x003C240B]\n\t(No symbol) [0x003B4FF7]\n\tBaseThreadInitThunk [0x751662C4+36]\n\tRtlSubscribeWnfStateChangeNotification [0x77341B69+1081]\n\tRtlSubscribeWnfStateChangeNotification [0x77341B34+1028]\n"}} | headers=HTTPHeaderDict({'Content-Length': '846', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
[DEBUG  ] Finished Request
 Exception in thread Thread-4:
 Traceback (most recent call last):
   File "threading.py", line 932, in _bootstrap_inner
   File "threading.py", line 870, in run
   File "utils\ressources.py", line 398, in generate_pdf_report
     driver = webdriver.Chrome(service=service, options=options)
   File "selenium\webdriver\chrome\webdriver.py", line 45, in __init__
   File "selenium\webdriver\chromium\webdriver.py", line 56, in __init__
   File "selenium\webdriver\remote\webdriver.py", line 206, in __init__
   File "selenium\webdriver\remote\webdriver.py", line 290, in start_session
   File "selenium\webdriver\remote\webdriver.py", line 345, in execute
   File "selenium\webdriver\remote\errorhandler.py", line 229, in check_response
 selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
 Stacktrace:
 Backtrace:
        GetHandleVerifier [0x0042A813+48355]
        (No symbol) [0x003BC4B1]
        (No symbol) [0x002C5358]
        (No symbol) [0x002E1A9E]
        (No symbol) [0x002E0579]
        (No symbol) [0x00310C55]
        (No symbol) [0x0031093C]
        (No symbol) [0x0030A536]
        (No symbol) [0x002E82DC]
        (No symbol) [0x002E93DD]
        GetHandleVerifier [0x0068AABD+2539405]
        GetHandleVerifier [0x006CA78F+2800735]
        GetHandleVerifier [0x006C456C+2775612]
        GetHandleVerifier [0x004B51E0+616112]
        (No symbol) [0x003C5F8C]
        (No symbol) [0x003C2328]
        (No symbol) [0x003C240B]
        (No symbol) [0x003B4FF7]
        BaseThreadInitThunk [0x751662C4+36]
        RtlSubscribeWnfStateChangeNotification [0x77341B69+1081]
        RtlSubscribeWnfStateChangeNotification [0x77341B34+1028]

**Comment by Alb-310** [comment]
Thx I will look into it! 
Just do you have Google Chrome on the device where you are running Geogramint ?
And on which OS are you using Geogramint ?

**Comment by Kafel23** [comment]
Win 10 64 bit and no, I don't have Chrome on my PC.
And look......the thing is that after one or two searches Telegram DELETES my account....-(. I've already lost two of them tday-((((

**Comment by Alb-310** [comment]
wtf 🤔 
I will look into it but it's very weird

**Comment by Alb-310** [comment]
apparently it's a known issue with Telethon ( the library that communicate with Telegram's API ) in some countries/IP. It's a strange bug 

>Even official applications have these problems, not only libraries. Bans probably depend on a lot of factors, such as country, IP, use of the application, maybe even some random bans to accounts so people who care recover them and spambots won't bother with emails so those are gone, etc. For completeness sake:
>
>Emails: [login@stel.com](mailto:login@stel.com), [recover@telegram.org](mailto:recover@telegram.org).
>
>If those don't work, [abuse@telegram.org](mailto:abuse@telegram.org), https://telegram.org/support and DM to https://twitter.com/smstelegram may be worth trying.

cf [#824](https://github.com/lonamiwebs/telethon/issues/824#issuecomment-432182634)
[#3861](https://github.com/LonamiWebs/Telethon/issues/3861)

**Comment by Kafel23** [comment]
Done.....Uploaded Google Chrome. Thanks for advice and good tool -)

**Comment by Alb-310** [comment]
Thx! I will work on a fix so the reports can be generated without chrome

**Comment by sssaaalah102** [comment]
hello i need user name of grop

**Comment by majnhmist** [comment]
everything is normal, and the output is always "NOTHING Found"

**Comment by Alb-310** [comment]
Bug fixed in last update [1.4](https://github.com/Alb-310/Geogramint/releases/tag/1.4) @Kafel23
