### ISSUE TITLE
Problem with output

### ISSUE THREAD

**Issue by sai84** [Alb-310/Geogramint#17]
Hi! Everything works, but the output doesn't. Here is the error:

TypeError: __init__() got an unexpected keyword argument 'path'

And here is the input:

python3 geogramint.py start-scan --output-pdf / 99.999999 99.8999999

**Comment by Alb-310** [comment]
Hello, thx for reporting this bug! I will fix it soon

**Comment by Alb-310** [comment]
Bug fixed in last update [1.4](https://github.com/Alb-310/Geogramint/releases/tag/1.4)
