### ISSUE TITLE
Stuck at settings

### ISSUE THREAD

**Issue by hevold** [Alb-310/Geogramint#20]
Promising tool! I installed the latest version, put in my details, but I still get stuck in settings. I´m on Mac, Python 3.11.4
![Skjermbilde 2023-11-11 kl  09 53 15](https://github.com/Alb-310/Geogramint/assets/77631307/e0980241-cc0e-4a76-ae7a-98238bece3bc)

**Comment by Alb-310** [comment]
Hello, thx! I will need some logs to be able to help you with your problem @hevold
