### ISSUE TITLE
Yad - Ubuntu Freezing

### ISSUE THREAD

**Issue by orekidev** [Alb-310/Geogramint#23]
First of all.....that osinttracker export tool seems absolutely ace....what a killer! 

Little issue here. Installed Geogramint on CSI Linux (ubuntu-based), but whenever the search is complete, yad / the export tool appears to completely freeze and force me to reboot the CSI VM......any idea why this would be? 

The export tool does create the navigator pop up on yad, but no click/enter/action appears to trigger anything...tried to sudo apt upgrade yad and associated components but no luck...thank you team!

**Comment by Alb-310** [comment]
Hello, do you have any logs when it freezes?

**Comment by orekidev** [comment]
Good morning,

My apologies for the belated response, I've been quite busy recently......! I'll have a look at the logs and push them as a response on Github asap.

Again, thank you for the fantastic tool!
