### ISSUE TITLE
[INFO   ] [Geogramint Search] Nothing Found

### ISSUE THREAD

**Issue by GreenAA** [Alb-310/Geogramint#26]
thank , but the app not find any 

https://github.com/Alb-310/Geogramint/assets/87846163/6cfff961-5e2c-4560-93e4-3a9451fa7af3

08378393, 'seq': 601, 'takeout_id': 0}, channel_states = []
[DEBUG  ] Assigned msg_id = 7337429328907692688 to GetLocatedRequest (195eed65e80)
[DEBUG  ] Encrypting 1 message(s) in 52 bytes for sending
[DEBUG  ] Encrypted messages put in a queue to be sent
[DEBUG  ] Waiting for messages to send...
[DEBUG  ] Assigned msg_id = 7337429328927726528 to MsgsAck (195fbda5b20)
[DEBUG  ] Encrypting 1 message(s) in 36 bytes for sending
[DEBUG  ] Encrypted messages put in a queue to be sent
[DEBUG  ] Waiting for messages to send...
[DEBUG  ] Handling RPC result for message 7337429328907692688
[DEBUG  ] Receiving items from the network...
[DEBUG  ] Assigned msg_id = 7337429329758416912 to MsgsAck (195fbec6af0)
[DEBUG  ] Encrypting 1 message(s) in 36 bytes for sending
[DEBUG  ] Encrypted messages put in a queue to be sent
[DEBUG  ] Waiting for messages to send...
[DEBUG  ] Assigned msg_id = 7337429329771153232 to MsgsAck (195f98bef40)
[DEBUG  ] Encrypting 1 message(s) in 36 bytes for sending
[DEBUG  ] Handling update UpdateShort
[DEBUG  ] Receiving items from the network...
[INFO   ] [Geogramint Search] Nothing Found

**Comment by GreenAA** [comment]
https://github.com/Alb-310/Geogramint/assets/87846163/12121764-9779-4b4e-97e0-fe11f62fd345

**Comment by Alb-310** [comment]
Hello, on which OS are you ?

**Comment by GreenAA** [comment]
Hi , thanks for replay 

win 11

**Comment by Alb-310** [comment]
You installed the tool using the installer or directly with the repository from github and used python ?

**Comment by GreenAA** [comment]
i download it the file for win - geogramin.exe and file install it and the 
`https://github.com/Alb-310/Geogramint`

i have vs code i try open it with python 8 / 9 / 10 / 11 / 12 and exe file not connec is stuck 

also i install direcly with git clone link and is open all ok but don't find nothing

**Comment by Alb-310** [comment]
On Telegram, do your privacy settings looks like this ?

https://github.com/Alb-310/Geogramint/blob/master/.github/privacy_settings.jpg

**Comment by GreenAA** [comment]
ahh no , private

**Comment by Alb-310** [comment]
That's why it is not working. Telegram blocks the use of nearby feature if the profile picture is private

**Comment by GreenAA** [comment]
thanks bro , excellent geogramint app

**Comment by GreenAA** [comment]
work perfect now thanks
