### ISSUE TITLE
ModuleNotFoundError: No module named 'kivy'

### ISSUE THREAD

**Issue by andre-santos1** [Alb-310/Geogramint#3]
I´m running Geogramint in Ubuntu 22.04 LTS with Python 3.10.4 and I´m getting the following error:

_osint@osint:~/Programas/Geogramint$ python3 geogramint.py 

Traceback (most recent call last):

  File "/home/osint/Programas/Geogramint/geogramint.py", line 7, in <module>

    from api import TelegramAPIRequests

  File "/home/osint/Programas/Geogramint/api/TelegramAPIRequests.py", line 4, in <module>

    from kivy import Logger

ModuleNotFoundError: No module named 'kivy'_

**Comment by Alb-310** [comment]
Hello @andre-santos1,

As written in the README and the Wiki, it's recommended to use python 3.8 or 3.9 with Geogramint. Kivy, the library responsible of the user interface have some problems in python 3.10.
Also make sure you installed all dependencies before running geogramint.py

**Comment by andre-santos1** [comment]
Thanks!
