### ISSUE TITLE
install requirements error.

### ISSUE THREAD

**Issue by dreuben79** [Alb-310/Geogramint#32]
Hi there, I'm getting this error when trying to install requirements.txt:

Collecting reportlab<4,>=3.5.53 (from xhtml2pdf==0.2.11->-r requirements.txt (line 2))
  Using cached reportlab-3.6.13.tar.gz (4.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      ##### setup-python-3.12.2-macosx-10.9-universal2: ================================================
      ##### setup-python-3.12.2-macosx-10.9-universal2: Attempting build of _rl_accel
      ##### setup-python-3.12.2-macosx-10.9-universal2: extensions from 'src/rl_addons/rl_accel'
      ##### setup-python-3.12.2-macosx-10.9-universal2: ================================================
      ##### setup-python-3.12.2-macosx-10.9-universal2: ===================================================
      ##### setup-python-3.12.2-macosx-10.9-universal2: Attempting build of _renderPM
      ##### setup-python-3.12.2-macosx-10.9-universal2: extensions from 'src/rl_addons/renderPM'
      ##### setup-python-3.12.2-macosx-10.9-universal2: ===================================================
      ##### setup-python-3.12.2-macosx-10.9-universal2: will use package libart 2.3.21
      !!!!! cannot find ft2build.h
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

---------

And then this when I try to run geogramint.py:

Traceback (most recent call last):
  File "/Users/danilo/Documents/Python_Projects/Geogramint/geogramint/Geogramint/geogramint.py", line 5, in <module>
    import trio
ModuleNotFoundError: No module named 'trio'

Any help would be much appreciated!

**Comment by Alb-310** [comment]
Hello, sorry for the late reply, can you try using an older version of python ? Python 3.9, 3.10 or 3.11
