### ISSUE TITLE
ModuleNotFoundError: No module named 'trio'

### ISSUE THREAD

**Issue by andre-santos1** [Alb-310/Geogramint#4]
New try here!

I´ve installed anaconda to run Python 3.9. 

But now I´m getting the following error wen I run :_python3 geogramint.py_:

_Traceback (most recent call last):

  File "/home/osint/Programas/Geogramint/geogramint.py", line 3, in <module>

    import trio

ModuleNotFoundError: No module named 'trio'_

**Comment by Alb-310** [comment]
Hello @andre-santos1,

Are you sure you installed all dependencies correctly ?

**Comment by andre-santos1** [comment]
Thanks for your patience. 

Well, I ran pip install -r requirements.txt

Should I do anything else in order to install dependencies?

**Comment by Alb-310** [comment]
try `pip3.9 install -r requirements.txt`, it seams since you have multiple versions of python you are getting problems.

**Comment by andre-santos1** [comment]
I will! Thanks
