### ISSUE TITLE
ImportError: cannot import name 'ressources' from 'utils'

### ISSUE THREAD

**Issue by gimmel** [Alb-310/Geogramint#5]
I cant’t start Geogramint with "python3 geogramint.py" on OS X. This is the console output:

Geogramint % python3 geogramint.py           
[INFO   ] [Logger      ] Record log in ~/.kivy/logs/kivy_22-09-04_3.txt
[INFO  ] [Kivy       ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/opt/homebrew/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.13 (main, May 24 2022, 21:13:51) 
[Clang 13.1.6 (clang-1316.0.21.2)]
[INFO   ] [Python      ] Interpreter at "/opt/homebrew/opt/python@3.9/bin/python3.9"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
 Traceback (most recent call last):
   File "~/Geogramint/geogramint.py", line 7, in <module>
     from api import TelegramAPIRequests
   File "~/Geogramint/api/TelegramAPIRequests.py", line 8, in <module>
     from utils import ressources
 ImportError: cannot import name 'ressources' from 'utils' (/opt/homebrew/lib/python3.9/site-packages/utils.py)

Sorry, some lines are strikes through because of markdown syntax.

**Comment by Alb-310** [comment]
Hello @gimmel,

Did you correctly cloned or download the repository ?
Did you installed all the dependencies ?

The bug is weird, your python is confusing the folder `utils` with the python lib named `utils`

**Comment by gimmel** [comment]
Oh, sorry, saw your answer too late.
I followed exactly your installation guide.
```
git clone https://github.com/Alb-310/Geogramint.git
cd Geogramint/
pip3 install -r requirements.txt
python3 geogramint.py
```
Running macOS 12.5.1 on a MacBook Pro 14" M1 with Python 3.10.6

**Comment by Alb-310** [comment]
You are still getting the same error ?

**Comment by Alb-310** [comment]
@gimmel if you still got the same error try this: https://stackoverflow.com/questions/58084072/python-module-not-found-but-exists-in-folder

Like that:
Before doing `cd Geogramint`
```
cd ~/Geogramint && export PYTHONPATH=$(pwd)

cd ~/Geogramint && export PATH=$PATH:$(pwd)

**Comment by gimmel** [comment]
Strange. I removed the Geogramint directory and reinstalled it. Now it suddenly works.
Thank you for taking a look.

**Comment by Alb-310** [comment]
Welcome 👍🏻
