### ISSUE TITLE
throws out

### ISSUE THREAD

**Issue by Mogerto** [Alb-310/Geogramint#7]
throws out at the search stage. Tried different accounts, but the problem is everywhere. You just start searching and exiting telegrams.

**Comment by Alb-310** [comment]
can you develop ?
I need more details to understand your problem

**Comment by NoPlagiarism** [comment]
Same problem

**Comment by NoPlagiarism** [comment]
Please, reopen this. I guess I found the problem

https://github.com/LonamiWebs/Telethon/issues/4051

**Comment by NoPlagiarism** [comment]
Answers that could help:

https://github.com/LonamiWebs/Telethon/issues/4051#issuecomment-1491747149
https://github.com/LonamiWebs/Telethon/issues/4051#issuecomment-1497634201
https://github.com/LonamiWebs/Telethon/issues/4051#issuecomment-1519075419

**Comment by Alb-310** [comment]
> Same problem

Hello, I need more details and context on the issue

**Comment by NoPlagiarism** [comment]
> I need more details and context on the issue

It's just as is. You can scroll mentioned issue on telethon about why it's happening (TL:DR - Telegram servers found a suspicious connection and terminating it along with other sessions)

It can be fixed adding those parameters to `TelegramClient`

```python
dict(
    device_model = "A320MH",          # On PC, device_model usually means motherboard
    app_version = "2.1.4a",                 # Typed a random semantic version
    system_version = "Windows 11",  # I guess any OS is ok. In issues above there's a mention of any "4.16.30-vxCUSTOM"
    lang_code = "en",
    system_lang_code = "fr-FR"          # Any random language codes
)
```

**Comment by NoPlagiarism** [comment]
Also, @Alb-310, what exactly details and context do you need?

**Comment by Alb-310** [comment]
> Also, @Alb-310, what exactly details and context do you need?

Screenshots or logs. I will investigate this issue but it will be difficult to solve since any of my accounts are impacted so it's hard to test if it's solved

**Comment by NoPlagiarism** [comment]
It doesn't leave any proper logs (as I remember) and it's hard to reproduce. It's just happens randomly, maybe sus accounts, such as accounts in spam ban (mine has one), are more in danger, than other

I fixed that problem once using parameters above, and now I even can't even reproduce it again

**Comment by NoPlagiarism** [comment]
Oh... I reproduced it (using CLI). It happened after search, so it really didn't leave any logs

**Comment by Alb-310** [comment]
Okay I see 🤔 Thanks I will investigate and try to fix the issue

**Comment by Alb-310** [comment]
Hello @NoPlagiarism, I added all parameters to TelegramClient in [1.4](https://github.com/Alb-310/Geogramint/releases/tag/1.4) hopefully it fixes the problem 👍
