### ISSUE TITLE
openGL 2 "missing"

### ISSUE THREAD

**Issue by savethekiddes** [Alb-310/Geogramint#8]
So I installed Geogramint via the Windows installer and it says that I don't have OpenGL 2.0 installed on my PC. It seems that he's using integrated graphics instead of the 3050 that I have. I tried forcing to use the 3050 in the graphic options, but the problem doesn't go away. I've the latest Game Ready driver, which obviously support OpenGL 2.X. Could you please giv me some advice? Thanks.

**Comment by Alb-310** [comment]
Hello,
Can you provide please some screenshots of the error ?

**Comment by savethekiddes** [comment]
![Here](https://i.ibb.co/vVkwLF6/Screenshot-20221228-104657.png)

**Comment by savethekiddes** [comment]
(I tried forcing Python too to use the 3050)

**Comment by Alb-310** [comment]
Do you have the last drivers on your 3050 ?

**Comment by savethekiddes** [comment]
As I told you, yes.

>  I've the latest Game Ready driver, which obviously support OpenGL 2.X

**Comment by Alb-310** [comment]
Is it possible for you to launch Geogramint using python instead of the .exe ?

If yes, I need you to try adding in geogramint.py 
```
import os
os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'
```

**Comment by savethekiddes** [comment]
Ok problem solved by going into envoirnment variables and setting:

`KIVY_GL_BACKEND` to `angle_sdl2`

**Comment by savethekiddes** [comment]
Ok problem solved by going into envoirnment variables and setting:

`KIVY_GL_BACKEND` to `angle_sdl2`

**Comment by Alb-310** [comment]
Perfect 👌🏻
I will add this to the FAQ on the wiki
